export type Feature = { icon: string[]; title: string; body: string; span?: boolean };

export const features: Feature[] = [
  {
    icon: ["11.1.11", "11.1.11", ".......", "11.1.11", "11.1.11", ".......", "1111111"],
    title: "Multiple chatrooms, one window",
    body: "Tabs with drag and drop reordering, unread counters and live status. Stream tabs can sit on the top, left or right.",
    span: true,
  },
  {
    icon: ["..1.1..", ".1.1.1.", "1.1.1.1", ".1.1.1.", "1.1.1.1", ".1.1.1.", "..1.1.."],
    title: "Overlay popup",
    body: "Overlay a chat window with transparency over a stream for an immersive experience.",
  },
  {
    icon: [".11111.", "1.....1", "1.1.1.1", "1.....1", "1.111.1", "1.....1", ".11111."],
    title: "7TV",
    body: "Global, channel and personal emote sets. Zero width overlays, paints and badges render the way 7TV intends.",
  },
  {
    icon: ["1111111", "1.....1", "1.1.1.1", "1.....1", "1.....1", "1..1..1", "1111111"],
    title: "Emotes everywhere",
    body: "Kick and subscriber emotes, emoji, pickers and :name / @user autocompletion. Typed emotes render inline in the input.",
  },
  {
    icon: ["...1...", "..111..", ".11111.", "1111111", "...1...", "...1...", "...1..."],
    title: "Built for speed",
    body: "Virtualised message list, cached parsing and async image pipeline with disk and GPU caching.",
    span: true,
  },
  {
    icon: [".11111.", "1.....1", "1.1.1.1", "1.....1", ".1...1.", "..1.1..", "...1..."],
    title: "Moderation tools",
    body: "User cards with channel message history, quick mod actions, slash commands, and mod events logs",
  },
  {
    icon: ["1111111", "1.....1", "1.11..1", "1.11..1", "1.....1", "1111111", "1.1.1.1"],
    title: "Clips",
    body: "/clip [seconds] [title] captures the last 10 to 180 seconds of stream and pops up a shareable link.",
  },
  {
    icon: ["..111..", ".1...1.", "1.....1", "1.....1", ".1...1.", "..111.1", ".....11"],
    title: "Stay in the loop",
    body: "Reply threads, search, chatters list, mentions tab and highlight phrases with custom sounds.",
  },
  {
    icon: ["1......", "11.....", "111....", "1111...", "11111..", "111111.", "1111111"],
    title: "Native desktop",
    body: "Always on top, frameless window with a custom title bar.",
  },
  {
    icon: ["..1.1..", "..1.1..", "1111111", ".1...1.", "1111111", "..1.1..", "..1.1.."],
    title: "Easy sign in",
    body: "Import your Kick session straight from your browser, with manual login methods as fallbacks.",
  },
];

export const commands: { cmd: string; desc: string; role?: string }[] = [
  { cmd: "/ban <user>", desc: "Permanently ban a user" },
  { cmd: "/unban <user>", desc: "Remove a ban or timeout" },
  { cmd: "/timeout <user> [minutes]", desc: "Timeout a user, default 5 minutes" },
  { cmd: "/clear", desc: "Clear chat history for everyone" },
  { cmd: "/slow [seconds]", desc: "Enable slow mode, default 6 seconds" },
  { cmd: "/slowoff", desc: "Disable slow mode" },
  { cmd: "/followers [minutes]", desc: "Enable followers only mode" },
  { cmd: "/followersoff", desc: "Disable followers only mode" },
  { cmd: "/subonly", desc: "Enable subscribers only mode" },
  { cmd: "/subonlyoff", desc: "Disable subscribers only mode" },
  { cmd: "/emoteonly", desc: "Enable emote only mode" },
  { cmd: "/emoteonlyoff", desc: "Disable emote only mode" },
  { cmd: "/mod <user>", desc: "Add a moderator", role: "broadcaster" },
  { cmd: "/unmod <user>", desc: "Remove a moderator", role: "broadcaster" },
  { cmd: "/vip <user>", desc: "Add a VIP", role: "broadcaster" },
  { cmd: "/unvip <user>", desc: "Remove a VIP", role: "broadcaster" },
  { cmd: "/host <channel>", desc: "Host another channel", role: "broadcaster" },
  { cmd: "/raid <channel>", desc: "Raid another channel", role: "broadcaster" },
  { cmd: "/category [name]", desc: "Change the stream category", role: "broadcaster" },
  { cmd: "/clip [seconds] [title]", desc: "Clip the last 10 to 180 seconds" },
];

export const shortcuts: [string, string][] = [
  ["Ctrl T", "Add a channel"],
  ["Ctrl F", "Search chatroom"],
  ["Ctrl P", "Open settings"],
  ["F5", "Refresh emotes"],
  ["Tab", "Accept suggestion"],
  ["Ctrl Enter", "Send with suggestions open"],
  ["Esc", "Close picker or reply"],
  ["Middle click", "Close tab or open stream"],
  ["Ctrl click", "Insert recent emote"],
];

export type ChatUser = { name: string; color: string };

export const chatUsers: ChatUser[] = [
  { name: "Hydroponicz", color: "#00ff88" },
  { name: "JasonStyles", color: "#f0b232" },
  { name: "Gaben", color: "#ff5c5c" },
  { name: "Keeks", color: "#ff9c3a" },
  { name: "Politecatguy", color: "#c74bff" },
  { name: "Tachys", color: "#00d0ff" },
  { name: "Colitepat", color: "#4bd6ff" },
  { name: "Surprisingduck", color: "#ffffff" },
  { name: "MericKat", color: "#ff5c5c" },
  { name: "politecats", color: "#00ff88" },
  { name: "PogTX", color: "#c74bff" },
  { name: "enzonik", color: "#00d0ff" },
  { name: "PatWiFi", color: "#f0b232" },
  { name: "twoslav", color: "#4bd6ff" },
  { name: "ouis", color: "#ff9c3a" },
  { name: "tjcool", color: "#00ff88" },
  { name: "RealityDOSE", color: "#ff5c5c" },
];

export const chatMessages = [
  "bro what are you doing",
  "NO SHOT",
  "nah this is crazy",
  "wait what",
  "BRO",
  "he actually did it",
  "aintnoway",
  "why did he do that",
  "this guy is insane",
  "chat are we serious",
  "WHAT",
  "nah bro",
  "just play the game",
  "he is throwing",
  "this is painful",
  "how does he keep getting away with this",
  "bro thinks hes cooking",
  "let him cook",
  "never let him cook again",
  "okay that was clean",
  "THAT WAS CLEAN",
  "bro is locked in",
  "hes actually focused",
  "rare focus moment",
  "no way he saw that",
  "how did he see that",
  "actual gigabrain",
  "5Head play",
  "that was lucky",
  "pure luck",
  "skill issue",
  "massive skill issue",
  "bro missed that",
  "HOW DO YOU MISS THAT",
  "my eyes",
  "im losing it",
  "chat im done",
  "this stream is cooked",
  "we are so back",
  "its over",
  "its actually over",
  "never doubted him",
  "i doubted him",
  "i knew that was happening",
  "called it",
  "bro is trolling",
  "hes definitely trolling",
  "there is no way this is intentional",
  "surely",
  "surely he wins this",
  "no shot he loses",
  "he lost",
  "classic",
  "every single time",
  "why is this happening",
  "bro please",
  "PLEASE",
  "just leave",
  "RUN",
  "TURN AROUND",
  "behind you",
  "LOOK BEHIND YOU",
  "bro is blind",
  "he cannot hear us",
  "chat is useless",
  "someone tell him",
  "WE TRIED",
  "we told you",
  "chat literally warned you",
  "he ignored chat",
  "average chat interaction",
  "this is cinema",
  "absolute cinema",
  "what am i watching",
  "why am i still here",
  "i cant stop watching",
  "this is better than tv",
  "peak content",
  "content is content",
  "bro found content",
  "this is going to be a clip",
  "someone clip that",
  "CLIP IT",
  "that needs to be clipped",
  "mods clip that",
  "editor is gonna love this",
  "there is no way",
  "NO WAY",
  "BRO NO",
  "WHAT JUST HAPPENED",
  "did anyone else see that",
  "i blinked",
  "i looked away for one second",
  "what happened",
  "can someone explain",
  "context?",
  "I JUST GOT HERE",
  "what did i miss",
  "new frogs what happened",
  "bro joined at the worst time",
  "perfect timing",
  "welcome to the stream",
  "you missed everything",
  "you missed nothing",
  "same stream different day",
  "how long has this been happening",
  "3 hours of this",
  "we have been here for 6 hours",
  "he has been doing this all day",
  "bro has not learned",
  "he never learns",
  "why does he keep doing that",
  "because it works",
  "it literally works",
  "DO IT AGAIN",
  "do it again bro",
  "one more time",
  "run it back",
  "again",
  "again again",
  "that was so bad",
  "that was actually terrible",
  "worst play ive ever seen",
  "ive seen enough",
  "pack it up",
  "go next",
  "NEXT GAME",
  "just queue again",
  "we go again",
  "run another one",
  "one more",
  "last game",
  "surely last game",
  "we all know its not the last game",
  "bro said last game 4 hours ago",
  "classic last game",
  "he is not getting off",
  "hes gonna be here all night",
  "sleep schedule is finished",
  "there goes tomorrow",
  "bro has work tomorrow",
  "someone tell him to sleep",
  "sleep is optional",
  "health is temporary",
  "this is more important",
  "priorities",
  "chat is enabling this",
  "we are making it worse",
  "this is our fault",
  "we created this monster",
  "bro is actually addicted",
  "just one more game",
  "famous last words",
  "that was personal",
  "he wanted that guy",
  "bro remembered that name",
  "revenge arc",
  "villain arc",
  "character development",
  "new arc starting",
  "this is the turning point",
  "we are witnessing history",
  "history will remember this",
  "generational gameplay",
  "generational throw",
  "hall of fame throw",
  "worst decision possible",
  "literally why",
  "WHY",
  "why would you do that",
  "who told him to do this",
  "chat did not tell you to do that",
  "dont blame chat",
  "chat catching strays",
  "mods are sleeping",
  "mods wake up",
  "MODS",
  "someone ban this guy",
  "what did he say",
  "mods check that",
  "that guy again",
  "same guy every stream",
  "how is he still here",
  "bro is dedicated",
  "respect the commitment",
  "bro has been typing for 3 hours",
  "he is never going to stop",
  "chat moving too fast",
  "I CANT READ",
  "slow mode",
  "there are 40k people typing",
  "chat is flying",
  "impossible to read chat",
  "bro is reading one message every 5 minutes",
  "pain",
  "actual pain",
  "i waited 20 minutes for that",
  "worth it",
  "not worth it",
  "absolutely worth it",
  "best stream today",
  "worst stream today",
  "this stream is undefeated",
  "today is different",
  "same old",
  "nothing ever changes",
  "bro is farming clips",
  "he knows exactly what hes doing",
  "he definitely knows",
  "theres no way he doesnt know",
  "he is baiting chat",
  "classic bait",
  "we fell for it",
  "chat fell for it",
  "dont fall for it",
  "DONT REACT",
  "stop reacting",
  "hes farming you guys",
  "hes farming reactions",
  "chat is getting farmed",
  "we are getting farmed",
  "free content",
  "free reactions",
  "this is so obvious",
  "how are people falling for this",
  "every time",
  "literally every time",
  "he got them",
  "got em",
  "that was bait",
  "obvious bait",
  "obvious ragebait",
  "chat is cooked",
  "chat has fallen",
  "we are finished",
  "its joever",
  "we are back",
  "massive comeback",
  "COMEBACK",
  "THE COMEBACK",
  "HE DID IT",
  "I CANT BELIEVE IT",
  "actual miracle",
  "that should not have worked",
  "there is no universe where that works",
  "somehow it worked",
  "i was certain he was dead",
  "how",
  "HOW",
  "explain that",
  "that makes zero sense",
  "game is rigged",
  "this game is so broken",
  "developers watching this",
  "devs please fix",
  "not the games fault",
  "bro blaming the game",
  "classic blame",
  "take responsibility",
  "just admit it",
  "he will never admit it",
  "he never admits anything",
  "bro always has an excuse",
  "the excuse is crazy",
  "that excuse makes no sense",
  "we believe you bro",
  "sure bro",
  "okay buddy",
  "whatever you say",
  "thats crazy",
  "interesting",
  "very interesting",
  "hmm",
  "chat what do we think",
  "chat decide",
  "poll it",
  "POLL",
  "we need a poll",
  "ask chat",
  "chat knows",
  "chat does not know",
  "never ask chat",
  "worst possible question",
  "chat will make it worse",
  "this is democracy",
  "democracy has failed",
  "chat has spoken",
  "its unanimous",
  "we all agree",
  "no one agrees",
  "what is going on",
  "nobody knows",
  "not even he knows",
  "bro is lost",
  "he has no idea",
  "bro forgot the controls",
  "did he just forget",
  "learning curve",
  "hes learning",
  "progress",
  "huge progress",
  "zero progress",
  "we learned nothing",
  "back to square one",
  "day one gameplay",
  "tutorial gameplay",
  "NPC behavior",
  "actual NPC",
  "bro is moving like an NPC",
  "what is that movement",
  "movement is insane",
  "mechanics are crazy",
  "aim is cooked",
  "aim diff",
  "massive aim diff",
  "he is getting diffed",
  "this guy is better",
  "just accept it",
  "run away",
  "fight him",
  "WHY ARE YOU RUNNING",
  "WHY ARE YOU FIGHTING",
  "make up your mind",
  "pick one",
  "bro cannot decide",
  "decision making is cooked",
  "that was the wrong choice",
  "right choice",
  "perfect choice",
  "fivehead",
  "actual genius",
  "he planned that",
  "he planned all of it",
  "master plan",
  "4D chess",
  "he is three steps ahead",
  "we are not ready",
  "chat is not ready",
  "i was not ready",
  "nobody was ready",
  "WHAT A PLAY",
  "insane play",
  "that was disgusting",
  "absolutely filthy",
  "clean",
  "so clean",
  "perfect",
  "literally perfect",
  "nothing you can do",
  "unlucky",
  "so unlucky",
  "thats tragic",
  "actually tragic",
  "rough",
  "thats rough",
  "tough scene",
  "thats unfortunate",
  "you hate to see it",
  "you love to see it",
  "we take those",
  "huge",
  "massive",
  "gigantic",
  "colossal",
  "thats huge",
  "W play",
  "massive W",
  "big W",
  "common W",
  "common L",
  "massive L",
  "huge L",
  "take the L",
  "LMAO",
  "im crying",
  "i cant",
  "bro",
  "BROTHER",
  "my guy",
  "my brother",
  "what are we doing",
  "what is bro cooking",
  "bro is cooking something",
  "kitchen is closed",
  "get out of the kitchen",
  "chef is back",
  "chef is gone",
  "someone take the stove away",
  "the stove is on fire",
  "whole kitchen is burning",
  "this is unbelievable",
  "unbelievable scenes",
  "insane scenes",
  "what a sequence",
  "this cannot be real",
  "is this scripted",
  "scripted",
  "who wrote this",
  "writers are going crazy",
  "best episode yet",
  "season finale",
  "plot armor",
  "he has plot armor",
  "main character",
  "main character moment",
  "side character gameplay",
  "NPC arc",
  "villain arc confirmed",
  "redemption arc",
  "comeback arc",
  "training arc",
  "this is peak",
  "absolute peak",
  "peak gaming",
  "we are witnessing peak",
  "cinema",
  "10 out of 10",
  "best thing ive seen all week",
  "i just opened the stream",
  "first time here",
  "what game is this",
  "how long has he been playing",
  "is this a new game",
  "did he win yet",
  "did he lose yet",
  "who is that",
  "what happened to the other guy",
  "why is everyone mad",
  "why is chat spamming",
  "someone summarize",
  "give me the lore",
  "need context",
  "this is unreadable",
  "this game looks terrible",
  "never playing this",
  "how much is this game",
  "is it worth buying",
  "someone answer him",
  "he asked a question",
  "nobody answered",
  "chat failed",
  "chat never helps",
  "he should have googled it",
  "google exists",
  "just google it",
  "bro refuses to google",
  "why does he refuse to google",
  "this is painful to watch",
  "i looked away",
  "yep",
  "there it is",
  "nothing changes",
  "we go next",
  "one more surely",
  "surely this one",
  "this is the one",
  "trust",
  "trust the process",
  "believe",
  "have faith",
  "we believe",
  "never give up",
  "DO NOT GIVE UP",
  "HE CAN DO THIS",
  "wait",
  "WAIT",
  "WAIT WAIT WAIT",
  "hold on",
  "something is happening",
  "something happened",
  "NO",
  "YES",
  "I CANT",
  "THIS GUY",
  "WHAT A MOMENT",
  "THAT WAS INSANE",
  "no words",
  "speechless",
  "look at chat",
  "LOOK AT CHAT",
  "worth staying up for",
  "worth the wait",
  "i almost went to bed",
  "now end stream",
  "perfect ending",
  "dont end",
  "dont throw",
  "DONT THROW",
  "hes throwing again",
  "oh no",
  "its happening",
  "here we go",
  "here we go again",
  "we know how this ends",
  "i know exactly how this ends",
  "this is not ending well",
  "chat always knows",
  "he doesnt know",
  "he never knows",
  "please listen to chat",
  "for once listen to chat",
  "JUST LISTEN",
  "why wont he listen",
  "because chat is wrong",
  "chat is always wrong",
  "sometimes chat is right",
  "this is one of those times",
  "common streamer L",
  "another L",
  "another day another L",
  "nothing happened",
  "never happened",
  "delete the VOD",
  "nobody clip that",
  "DO NOT CLIP",
  "too late",
  "someone clipped it",
  "its already on twitter",
  "cant believe im still awake",
];
